services:
  db:
    image: postgres:16
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-cleaner:
    image: db_cleaner:latest
    build:
      context: .
      dockerfile: db_cleaner/Dockerfile
    environment:
      POSTGRES_HOST: db
    env_file: .env
    depends_on:
      - db

  migrations:
    image: alembic_migrations:latest
    build:
      context: .
      dockerfile: alembic/Dockerfile
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy

  app:
    image: fastapi_server:latest
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      POSTGRES_HOST: db
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - migrations

  price_tracker:
    image: price_tracker:latest
    build:
      context: .
      dockerfile: price_tracker/Dockerfile
    environment:
      POSTGRES_HOST: db
    env_file: .env
    depends_on:
      - app
  wordle_tracker:
    image: wordle_tracker:latest
    build:
      context: .
      dockerfile: wordle_tracker/Dockerfile
    environment:
      POSTGRES_HOST: db
    env_file: .env
    depends_on:
      - app

volumes:
  postgres_data: