services:
  db:
    image: postgres:16
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db-cleaner:
    image: db_cleaner:latest
    build:
      context: .
      dockerfile: db_cleaner/Dockerfile
    environment:
      POSTGRES_HOST: db
    env_file: .env
    depends_on:
      - db
  migrations:
    image: alembic_migrations:latest
    build:
      context: .
      dockerfile: alembic/Dockerfile
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
  app:
    image: fastapi_server:latest
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      POSTGRES_HOST: db
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - migrations
  price_tracker:
    image: price_tracker:latest
    build:
      context: .
      dockerfile: price_tracker/Dockerfile
    environment:
      POSTGRES_HOST: db
    env_file: .env
    depends_on:
      - app

volumes:
  postgres_data: