"""Add image to skins

Revision ID: 056da8286b8a
Revises: 18b16e8f94cb
Create Date: 2025-06-19 16:35:58.140668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '056da8286b8a'
down_revision: Union[str, None] = '18b16e8f94cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('image', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skins_id'), table_name='skins')
    op.drop_column('skins', 'image')
    # ### end Alembic commands ###
