"""Case_Skin model structure change

Revision ID: 136e94d9fbca
Revises: 81c1ca487732
Create Date: 2025-07-03 17:14:37.869926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136e94d9fbca'
down_revision: Union[str, None] = '81c1ca487732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_models', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('case_models', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('case_models', 'skin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_models', 'skin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('case_models', 'case_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('case_models', 'id')
    # ### end Alembic commands ###
