"""Created skin_model added balance to user

Revision ID: 18b16e8f94cb
Revises: ec2e66262d9b
Create Date: 2025-06-18 20:15:55.084418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b16e8f94cb'
down_revision: Union[str, None] = 'ec2e66262d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skins_id'), 'skins', ['id'], unique=False)
    op.add_column('users', sa.Column('balance', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    op.drop_index(op.f('ix_skins_id'), table_name='skins')
    op.drop_table('skins')
    # ### end Alembic commands ###
