"""add trackable to skins

Revision ID: 19681b2181f3
Revises: 98368d4d6af2
Create Date: 2025-08-03 14:58:44.599692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19681b2181f3'
down_revision: Union[str, None] = '98368d4d6af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('is_trackable', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skins', 'is_trackable')
    # ### end Alembic commands ###
