"""add unread messages

Revision ID: 1b778b705db8
Revises: 666a1224d335
Create Date: 2025-08-05 18:55:39.020158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b778b705db8'
down_revision: Union[str, None] = '666a1224d335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_chats', sa.Column('unread_messages', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_chats', 'unread_messages')
    # ### end Alembic commands ###
