"""fixed manytomany relationship

Revision ID: 1bdb38b21e90
Revises: de885b60c2e0
Create Date: 2025-06-30 12:10:21.850630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bdb38b21e90'
down_revision: Union[str, None] = 'de885b60c2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_models',
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('skin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], )
    )
    op.drop_table('user_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_roles',
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('user_roles_case_id_fkey')),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], name=op.f('user_roles_skin_id_fkey'))
    )
    op.drop_table('case_models')
    # ### end Alembic commands ###
