"""add requester_id to friends

Revision ID: 1c60287f206d
Revises: 0c51f678b719
Create Date: 2025-08-02 17:32:57.895983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c60287f206d'
down_revision: Union[str, None] = '0c51f678b719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('requester_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'friends', 'users', ['requester_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_column('friends', 'requester_id')
    # ### end Alembic commands ###
