"""add me and sigma to case model

Revision ID: 2145c4cc6aa4
Revises: 1bdb38b21e90
Create Date: 2025-06-30 15:19:36.619050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2145c4cc6aa4'
down_revision: Union[str, None] = '1bdb38b21e90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('math_exception', sa.Integer(), server_default='0', nullable=False))
    op.add_column('cases', sa.Column('sigma', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'sigma')
    op.drop_column('cases', 'math_exception')
    # ### end Alembic commands ###
