"""notificaton update

Revision ID: 42511cb230e5
Revises: 8b37e908a132
Create Date: 2025-08-03 20:56:11.543249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42511cb230e5'
down_revision: Union[str, None] = '8b37e908a132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_receiver_id', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('notification_sender_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('notifications_notification_receiver_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['notification_sender_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['notification_receiver_id'], ['id'])
    op.drop_column('notifications', 'notification_receiver')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_receiver', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_notification_receiver_fkey'), 'notifications', 'users', ['notification_receiver'], ['id'])
    op.drop_column('notifications', 'notification_sender_id')
    op.drop_column('notifications', 'notification_receiver_id')
    # ### end Alembic commands ###
