"""Updated user model

Revision ID: 514182fdb6c4
Revises: bd5951578a7e
Create Date: 2025-07-09 13:34:56.993178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514182fdb6c4'
down_revision: Union[str, None] = 'bd5951578a7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_creator', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('users', sa.Column('avatar', sa.String(), server_default='default.png', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'is_creator')
    # ### end Alembic commands ###
