"""add case opened cnt and author case opened cnt

Revision ID: 62defce1d751
Revises: 01f406731ad5
Create Date: 2025-07-23 19:27:24.955862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62defce1d751'
down_revision: Union[str, None] = '01f406731ad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('opened_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('author_case_opened', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'author_case_opened')
    op.drop_column('cases', 'opened_count')
    # ### end Alembic commands ###
