"""Changed  User_skin structure

Revision ID: 6d9b6531f8bb
Revises: d3ceade5c938
Create Date: 2025-07-03 13:08:46.291079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9b6531f8bb'
down_revision: Union[str, None] = 'd3ceade5c938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_skins_pkey', 'users_skins', type_='primary')
    op.add_column('users_skins', sa.Column('id', sa.Integer(), nullable=False, autoincrement=True))
    op.execute(sa.text("CREATE SEQUENCE users_skins_id_seq"))
    op.execute(sa.text("""
           UPDATE users_skins SET id = nextval('users_skins_id_seq')
       """))
    op.create_primary_key('users_skins_pkey', 'users_skins', ['id'])
    op.create_unique_constraint('uq_user_skin', 'users_skins', ['user_id', 'skin_id'])
    op.execute(sa.text("""
           ALTER TABLE users_skins 
           ALTER COLUMN id 
           SET DEFAULT nextval('users_skins_id_seq'::regclass)
       """))
    op.execute(sa.text("ALTER SEQUENCE users_skins_id_seq OWNED BY users_skins.id"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_skins_pkey', 'users_skins', type_='primary')
    op.drop_constraint('uq_user_skin', 'users_skins', type_='unique')
    op.drop_column('users_skins', 'id')
    op.execute(sa.text("DROP SEQUENCE users_skins_id_seq"))
    op.create_primary_key('users_skins_pkey', 'users_skins', ['user_id', 'skin_id'])
    # ### end Alembic commands ###
