"""Changed  User_skin structure

Revision ID: 6d9b6531f8bb
Revises: d3ceade5c938
Create Date: 2025-07-03 13:08:46.291079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9b6531f8bb'
down_revision: Union[str, None] = 'd3ceade5c938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_skins', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_skins', 'id')
    # ### end Alembic commands ###
