"""add players cnt

Revision ID: 6f036109fd65
Revises: c1cc5584fa91
Create Date: 2025-07-24 19:41:24.839574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f036109fd65'
down_revision: Union[str, None] = 'c1cc5584fa91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('players_cnt', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battles', 'players_cnt')
    # ### end Alembic commands ###
