"""add checked and edited marks

Revision ID: 77d05bbafa12
Revises: 1b778b705db8
Create Date: 2025-08-06 18:22:22.995950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d05bbafa12'
down_revision: Union[str, None] = '1b778b705db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_checked', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'is_checked')
    # ### end Alembic commands ###
