"""add statistics

Revision ID: 86355cd62ab9
Revises: 514182fdb6c4
Create Date: 2025-07-17 16:47:06.176078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86355cd62ab9'
down_revision: Union[str, None] = '514182fdb6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('case_opened', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('upgrades_cnt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('contracts_cnt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('successful_cases_cnt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('successful_contracts_cnt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('successful_upgrades_cnt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('cases_create', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cases_create')
    op.drop_column('users', 'successful_upgrades_cnt')
    op.drop_column('users', 'successful_contracts_cnt')
    op.drop_column('users', 'successful_cases_cnt')
    op.drop_column('users', 'contracts_cnt')
    op.drop_column('users', 'upgrades_cnt')
    op.drop_column('users', 'case_opened')
    # ### end Alembic commands ###
