"""add host

Revision ID: 9029eb99d88f
Revises: fda80f8f53a0
Create Date: 2025-07-25 17:18:13.369767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9029eb99d88f'
down_revision: Union[str, None] = 'fda80f8f53a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('host', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'battles', 'users', ['host'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'battles', type_='foreignkey')
    op.drop_column('battles', 'host')
    # ### end Alembic commands ###
