"""add cascade delete

Revision ID: 98368d4d6af2
Revises: adbcfa3e3cdc
Create Date: 2025-08-03 14:46:06.040452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98368d4d6af2'
down_revision: Union[str, None] = 'adbcfa3e3cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_battles_user_id_fkey'), 'users_battles', type_='foreignkey')
    op.drop_constraint(op.f('users_battles_battle_id_fkey'), 'users_battles', type_='foreignkey')
    op.create_foreign_key(None, 'users_battles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_battles', 'battles', ['battle_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_battles', type_='foreignkey')
    op.drop_constraint(None, 'users_battles', type_='foreignkey')
    op.create_foreign_key(op.f('users_battles_battle_id_fkey'), 'users_battles', 'battles', ['battle_id'], ['id'])
    op.create_foreign_key(op.f('users_battles_user_id_fkey'), 'users_battles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
