"""created battle model

Revision ID: a0facaa9614f
Revises: 62defce1d751
Create Date: 2025-07-24 19:00:10.710893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0facaa9614f'
down_revision: Union[str, None] = '62defce1d751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('is_started', sa.Boolean(), server_default='False', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_user', sa.Integer(), nullable=False),
    sa.Column('second_user', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['first_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['second_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_user', 'second_user', name='uix_friendship')
    )
    op.create_table('users_battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_battles')
    op.drop_table('friends')
    op.drop_table('battles')
    # ### end Alembic commands ###
