"""remove groups

Revision ID: a6b7164b12af
Revises: ab7eaf332060
Create Date: 2025-08-05 18:08:51.857094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b7164b12af'
down_revision: Union[str, None] = 'ab7eaf332060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'name')
    op.drop_column('chats', 'is_group')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_group', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
