"""add achievements cnt and battles won cnt

Revision ID: a9a5ab930183
Revises: 3af93e5f02f6
Create Date: 2025-08-11 15:12:36.607787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a5ab930183'
down_revision: Union[str, None] = '3af93e5f02f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('battles_won', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('battles_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('achievements_cnt', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users_achievements', sa.Column('achievement_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('users_achievements_chat_id_fkey'), 'users_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'users_achievements', 'achievements', ['achievement_id'], ['id'])
    op.drop_column('users_achievements', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_achievements', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users_achievements', type_='foreignkey')
    op.create_foreign_key(op.f('users_achievements_chat_id_fkey'), 'users_achievements', 'achievements', ['chat_id'], ['id'])
    op.drop_column('users_achievements', 'achievement_id')
    op.drop_column('users', 'achievements_cnt')
    op.drop_column('users', 'battles_streak')
    op.drop_column('users', 'battles_won')
    # ### end Alembic commands ###
