"""add created to battles

Revision ID: adbcfa3e3cdc
Revises: 1c60287f206d
Create Date: 2025-08-03 14:07:50.756673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adbcfa3e3cdc'
down_revision: Union[str, None] = '1c60287f206d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases_skins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('skin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('case_models')
    op.add_column('battles', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('battles', 'expires')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('expires', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('battles', 'created')
    op.create_table('case_models',
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('case_models_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('case_models_case_id_fkey')),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], name=op.f('case_models_skin_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_models_id'))
    )
    op.drop_table('cases_skins')
    # ### end Alembic commands ###
