"""upgraded battle model add cases relation and cnt

Revision ID: c1cc5584fa91
Revises: 32e7635962dd
Create Date: 2025-07-24 19:39:07.834896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cc5584fa91'
down_revision: Union[str, None] = '32e7635962dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('case_id', sa.Integer(), nullable=False))
    op.add_column('battles', sa.Column('case_cnt', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'battles', 'cases', ['case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'battles', type_='foreignkey')
    op.drop_column('battles', 'case_cnt')
    op.drop_column('battles', 'case_id')
    # ### end Alembic commands ###
