"""created battle model fixes

Revision ID: c67ba66ff93d
Revises: a0facaa9614f
Create Date: 2025-07-24 19:16:26.949964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c67ba66ff93d'
down_revision: Union[str, None] = 'a0facaa9614f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('first_user_id', sa.Integer(), nullable=False))
    op.add_column('friends', sa.Column('second_user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uix_friendship'), 'friends', type_='unique')
    op.create_unique_constraint('uix_friendship', 'friends', ['first_user_id', 'second_user_id'])
    op.drop_constraint(op.f('friends_second_user_fkey'), 'friends', type_='foreignkey')
    op.drop_constraint(op.f('friends_first_user_fkey'), 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'users', ['second_user_id'], ['id'])
    op.create_foreign_key(None, 'friends', 'users', ['first_user_id'], ['id'])
    op.drop_column('friends', 'second_user')
    op.drop_column('friends', 'first_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('first_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('friends', sa.Column('second_user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key(op.f('friends_first_user_fkey'), 'friends', 'users', ['first_user'], ['id'])
    op.create_foreign_key(op.f('friends_second_user_fkey'), 'friends', 'users', ['second_user'], ['id'])
    op.drop_constraint('uix_friendship', 'friends', type_='unique')
    op.create_unique_constraint(op.f('uix_friendship'), 'friends', ['first_user', 'second_user'], postgresql_nulls_not_distinct=False)
    op.drop_column('friends', 'second_user_id')
    op.drop_column('friends', 'first_user_id')
    # ### end Alembic commands ###
