"""add author_id to cases

Revision ID: d1e22d8bf075
Revises: 070be882d012
Create Date: 2025-07-23 12:24:12.640057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e22d8bf075'
down_revision: Union[str, None] = '070be882d012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'author_id')
    # ### end Alembic commands ###
