"""add battle price

Revision ID: fda80f8f53a0
Revises: 448d41d42d91
Create Date: 2025-07-24 20:20:58.559254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda80f8f53a0'
down_revision: Union[str, None] = '448d41d42d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('price', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battles', 'price')
    # ### end Alembic commands ###
