name: CI

on: [push]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install requirements.txt
        run:
          pip install -r requirements.txt
      - name: Run Flake8
        run:
          flake8 .
      - name: Run Tests
        run:
          pytest -v
